site_name: Location History Format
site_url: https://locationhistoryformat.com
repo_url: https://github.com/CarlosBergillos/LocationHistoryFormat
repo_name: "LocationHistoryFormat"
edit_uri: ""
docs_dir: docs
remote_branch: gh-pages

theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: white
    accent: pink
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  logo: static/timeline_blue_24dp.svg
  favicon: static/timeline_blue_24dp_favicon.svg
  icon:
    repo: fontawesome/brands/github

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/CarlosBergillos
  generator: false
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, 'G-319THE2V0E']

copyright: Copyright &copy; 2023 Carlos Bergillos

use_directory_urls: true

nav:
  - Home: index.md
  - Guides:
    - Downloading the Data: guides/downloading.md
    - General Structure: guides/general-structure.md
    - Raw Location History Data: guides/raw-location.md
    - Semantic Location History Data: guides/semantic-location.md
  - Reference:
    - reference/index.md
    - Records.json: reference/records.md
    - Settings.json: reference/settings.md
    - Timeline Edits.json: reference/timeline-edits.md
    - Semantic Location History: reference/semantic.md
  - FAQ: faq.md
  - Contributing: contributing.md

plugins:
  - search
  - git-revision-date
  - macros
